### ISSUE TITLE
10.10.2 Yosemite Postgresql fails to connect

### ISSUE THREAD

**Issue by brianjking** [hbokh/docker-jira-postgresql#3]
Error connecting to database

Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Connection refused

This is what I'm getting on OS X 10.10.2 Yosemite. Any suggestions?

**Comment by hbokh** [comment]
I'm sorry to say that I can not reproduce this error on a fresh (re-)build on OS X 10.10.2 Yosemite, like I just did...
Are you sure you're using the right credentials? Like: `["USER=super", "DB=jiradb", "PASS=p4ssw0rd"]`, hostname "db", etc.
And used a rebuilded PostgreSQL-container from latest Phusion baseimage + data-only container?

**Comment by brianjking** [comment]
@hbokh  -- Okay, I now followed the steps provided on your Docker Hub page verbatim and excluded Kitematic from the process entirely. When executing docker run -d --name jira -p 8080:8080 --link postgresql:db hbokh/docker-jira-postgresql I get an error message back 

bash-3.2$ docker run -d --name jira -p 8080:8080 --link postgresql:db hbokh/docker-jira-postgresql
FATA[0000] Error response from daemon: Conflict. The name "jira" is already in use by container 06f572676bad. You have to delete (or rename) that container to be able to reuse that name. 
bash-3.2$ 


Thoughts?

Thanks!

**Comment by hbokh** [comment]
Delete that container as suggested in the error-message: 'docker rm 06f572676bad'.
