### ISSUE TITLE
System reboot leaves tomcat with pidfile

### ISSUE THREAD

**Issue by d2a-raudenaerde** [hbokh/docker-jira-postgresql#5]
When shutting down the host system (in my case CentOS7) using 'reboot', the image containing tomcat will not properply shut down, leaving a pidfile that causes `docker start` to fail starting the container.

**Comment by wuchg** [comment]
I have exactly the same issue

**Comment by rept** [comment]
Same here, anybody know a solution for this?

**Comment by hbokh** [comment]
Sorry for the far too late replies, but I hardly work or even look at this project anymore.
I have added a kinda sloppy way to get rid of the pid-file in file `start-jira.sh`
Also marked the repo as retired and outdated.
